### ISSUE TITLE
executing a single query from the current file?

### ISSUE THREAD

**Issue by sentriz** [nanotee/sqls.nvim#1]
hey thanks for the plugin! it works really well

I wondering if it possible to do something like `:SqlsExecuteQuery` but for one query in the file? perhaps the one the cursor is on?
currently it seems to run them all in order

thanks!

**Comment by nanotee** [comment]
Glad to know this is useful! :)

`:SqlsExecuteQuery` should work in visual mode, simply select the query you want to execute and type the command

**Comment by sentriz** [comment]
it works! thank you

**Comment by sigzegv** [comment]
It would be easier to only run the query under the cursor, and have another command to run the full file, selecting a query to run only one is painful.

**Comment by nanotee** [comment]
It's true that it would be a nice feature, but the difficult part is figuring out what counts as "a query under the cursor", since multiple queries can be on the same line and one query can span multiple lines. That would probably have to be implemented as a custom command in the language server itself since it already has an AST.

The easier and more "naive" way to do this would be to simply execute the current line

**Comment by sigzegv** [comment]
Usually multiple queries on a same files should be separated by a semi colon which could be enough to detect the boundaries of a query (I think so)

**Comment by nanotee** [comment]
I found this neat text object, which should make it easier to select individual queries: https://25.wf/posts/2020-09-04-vim-markdown-text-object.html#bonus-sql-queries-text-object

Otherwise I really do think the feature should be implemented in the language server itself (or maybe with tree-sitter), it's hard to come up with regex-only solutions that handle every corner case
